// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Item in *Mega Menu → Menu Items → Child Links*
 */
export interface MegaMenuDocumentDataMenuItemsChildLinksItem {
  /**
   * Child Link Label field in *Mega Menu → Menu Items → Child Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter child link label
   * - **API ID Path**: mega_menu.menu_items[].child_links[].child_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  child_label: prismic.KeyTextField;

  /**
   * Child Link field in *Mega Menu → Menu Items → Child Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Select or enter a child link
   * - **API ID Path**: mega_menu.menu_items[].child_links[].child_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  child_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Item in *Mega Menu → Menu Items*
 */
export interface MegaMenuDocumentDataMenuItemsItem {
  /**
   * Menu Item Label field in *Mega Menu → Menu Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter menu item label
   * - **API ID Path**: mega_menu.menu_items[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Menu Item Link field in *Mega Menu → Menu Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Select or enter a link
   * - **API ID Path**: mega_menu.menu_items[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Has Mega Menu field in *Mega Menu → Menu Items*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: mega_menu.menu_items[].has_mega_menu
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  has_mega_menu: prismic.BooleanField;

  /**
   * Child Links field in *Mega Menu → Menu Items*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: mega_menu.menu_items[].child_links[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  child_links: prismic.NestedGroupField<
    Simplify<MegaMenuDocumentDataMenuItemsChildLinksItem>
  >;
}

/**
 * Content for Mega Menu documents
 */
interface MegaMenuDocumentData {
  /**
   * Menu Title field in *Mega Menu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter the main menu title
   * - **API ID Path**: mega_menu.menu_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  menu_title: prismic.KeyTextField;

  /**
   * Menu Items field in *Mega Menu*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: mega_menu.menu_items[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  menu_items: prismic.GroupField<
    Simplify<MegaMenuDocumentDataMenuItemsItem>
  > /**
   * Meta Title field in *Mega Menu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title for the mega menu used for SEO
   * - **API ID Path**: mega_menu.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Mega Menu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief description of the mega menu
   * - **API ID Path**: mega_menu.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;
}

/**
 * Mega Menu document from Prismic
 *
 * - **API ID**: `mega_menu`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MegaMenuDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<MegaMenuDocumentData>,
    "mega_menu",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | StatsCounterSlice
  | PlainTextSlice
  | TextAndImageSlice
  | FullWidthBannerSlice
  | NewsletterSignupSlice
  | FeatureGridAnimatedSlice
  | PricingTableSlice
  | ImageGallerySlice
  | ProductCarouselSlice
  | MultiColumnCardsSlice
  | FaqAccordionSlice;

type PageDocumentDataSlices1Slice = never;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices1[]
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices1: prismic.SliceZone<PageDocumentDataSlices1Slice>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

export type AllDocumentTypes = MegaMenuDocument | PageDocument;

/**
 * Primary content in *FAQ Accordion → Default → Primary*
 */
export interface FaqAccordionSliceDefaultPrimary {
  /**
   * Title field in *FAQ Accordion → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter the main title for the FAQ section
   * - **API ID Path**: faq_accordion.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Subtitle field in *FAQ Accordion → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter a subtitle or description
   * - **API ID Path**: faq_accordion.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtitle: prismic.RichTextField;

  /**
   * Allow Multiple Open field in *FAQ Accordion → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: faq_accordion.default.primary.allowMultiple
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  allowMultiple: prismic.BooleanField;

  /**
   * Show Icons field in *FAQ Accordion → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: faq_accordion.default.primary.showIcons
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  showIcons: prismic.BooleanField;

  /**
   * Text Alignment field in *FAQ Accordion → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: center
   * - **API ID Path**: faq_accordion.default.primary.alignment
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  alignment: prismic.KeyTextField;

  /**
   * Footer Text field in *FAQ Accordion → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter any additional footer text
   * - **API ID Path**: faq_accordion.default.primary.footerText
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  footerText: prismic.RichTextField;
}

/**
 * Primary content in *FAQ Accordion → Items*
 */
export interface FaqAccordionSliceDefaultItem {
  /**
   * Question field in *FAQ Accordion → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter the FAQ question
   * - **API ID Path**: faq_accordion.items[].question
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  question: prismic.KeyTextField;

  /**
   * Answer field in *FAQ Accordion → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter the FAQ answer
   * - **API ID Path**: faq_accordion.items[].answer
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  answer: prismic.RichTextField;

  /**
   * Icon field in *FAQ Accordion → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_accordion.items[].icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon: prismic.ImageField<never>;
}

/**
 * Default variation for FAQ Accordion Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default FAQ Accordion
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqAccordionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FaqAccordionSliceDefaultPrimary>,
  Simplify<FaqAccordionSliceDefaultItem>
>;

/**
 * Slice variation for *FAQ Accordion*
 */
type FaqAccordionSliceVariation = FaqAccordionSliceDefault;

/**
 * FAQ Accordion Shared Slice
 *
 * - **API ID**: `faq_accordion`
 * - **Description**: A collapsible FAQ section
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqAccordionSlice = prismic.SharedSlice<
  "faq_accordion",
  FaqAccordionSliceVariation
>;

/**
 * Primary content in *Feature Grid Animated → Default → Primary*
 */
export interface FeatureGridAnimatedSliceDefaultPrimary {
  /**
   * Title field in *Feature Grid Animated → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter the main title for the animated feature grid
   * - **API ID Path**: feature_grid_animated.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Subtitle field in *Feature Grid Animated → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter a subtitle or description
   * - **API ID Path**: feature_grid_animated.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtitle: prismic.RichTextField;

  /**
   * Number of Columns field in *Feature Grid Animated → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: 3
   * - **API ID Path**: feature_grid_animated.default.primary.columns
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  columns: prismic.NumberField;

  /**
   * Show Icons field in *Feature Grid Animated → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: feature_grid_animated.default.primary.showIcons
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  showIcons: prismic.BooleanField;

  /**
   * Show Images field in *Feature Grid Animated → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: feature_grid_animated.default.primary.showImages
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  showImages: prismic.BooleanField;

  /**
   * Text Alignment field in *Feature Grid Animated → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Choose the text alignment
   * - **Default Value**: center
   * - **API ID Path**: feature_grid_animated.default.primary.text_alignment
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  text_alignment: prismic.SelectField<"center" | "left" | "right", "filled">;

  /**
   * Footer Link field in *Feature Grid Animated → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link to view all features
   * - **API ID Path**: feature_grid_animated.default.primary.footerLink
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  footerLink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Footer Button Text field in *Feature Grid Animated → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: View All Features
   * - **API ID Path**: feature_grid_animated.default.primary.footerButtonText
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  footerButtonText: prismic.KeyTextField;
}

/**
 * Primary content in *Feature Grid Animated → Items*
 */
export interface FeatureGridAnimatedSliceDefaultItem {
  /**
   * Feature Title field in *Feature Grid Animated → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter the feature title
   * - **API ID Path**: feature_grid_animated.items[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Feature Grid Animated → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter the feature description
   * - **API ID Path**: feature_grid_animated.items[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Image field in *Feature Grid Animated → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_grid_animated.items[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Icon field in *Feature Grid Animated → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_grid_animated.items[].icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon: prismic.ImageField<never>;

  /**
   * Link field in *Feature Grid Animated → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link to learn more about this feature
   * - **API ID Path**: feature_grid_animated.items[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Button Text field in *Feature Grid Animated → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Learn More
   * - **API ID Path**: feature_grid_animated.items[].buttonText
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  buttonText: prismic.KeyTextField;

  /**
   * Features List field in *Feature Grid Animated → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter feature items (one per line)
   * - **API ID Path**: feature_grid_animated.items[].features
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  features: prismic.KeyTextField;
}

/**
 * Default variation for Feature Grid Animated Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default Animated Feature Grid
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeatureGridAnimatedSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeatureGridAnimatedSliceDefaultPrimary>,
  Simplify<FeatureGridAnimatedSliceDefaultItem>
>;

/**
 * Slice variation for *Feature Grid Animated*
 */
type FeatureGridAnimatedSliceVariation = FeatureGridAnimatedSliceDefault;

/**
 * Feature Grid Animated Shared Slice
 *
 * - **API ID**: `feature_grid_animated`
 * - **Description**: An animated grid layout showcasing features with scroll-triggered animations
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeatureGridAnimatedSlice = prismic.SharedSlice<
  "feature_grid_animated",
  FeatureGridAnimatedSliceVariation
>;

/**
 * Primary content in *Full Width Banner → Default → Primary*
 */
export interface FullWidthBannerSliceDefaultPrimary {
  /**
   * Desktop Background Image field in *Full Width Banner → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: full_width_banner.default.primary.backgroundImage
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  backgroundImage: prismic.ImageField<never>;

  /**
   * Mobile Background Image field in *Full Width Banner → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: full_width_banner.default.primary.mobileBackgroundImage
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  mobileBackgroundImage: prismic.ImageField<never>;

  /**
   * Title field in *Full Width Banner → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter the banner title
   * - **API ID Path**: full_width_banner.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Description field in *Full Width Banner → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter a description or subtitle
   * - **API ID Path**: full_width_banner.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Call to Action Text field in *Full Width Banner → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter button text
   * - **API ID Path**: full_width_banner.default.primary.callToActionText
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  callToActionText: prismic.KeyTextField;

  /**
   * Call to Action Link field in *Full Width Banner → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link for the CTA button
   * - **API ID Path**: full_width_banner.default.primary.callToActionLink
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  callToActionLink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Horizontal Position field in *Full Width Banner → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: center
   * - **API ID Path**: full_width_banner.default.primary.horizontalPosition
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  horizontalPosition: prismic.SelectField<
    "left" | "center" | "right",
    "filled"
  >;

  /**
   * Vertical Position field in *Full Width Banner → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: middle
   * - **API ID Path**: full_width_banner.default.primary.verticalPosition
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  verticalPosition: prismic.SelectField<"top" | "middle" | "bottom", "filled">;

  /**
   * Content Alignment field in *Full Width Banner → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Select the content alignment
   * - **Default Value**: left
   * - **API ID Path**: full_width_banner.default.primary.contentAlignment
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  contentAlignment: prismic.SelectField<"left" | "center" | "right", "filled">;
}

/**
 * Default variation for Full Width Banner Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default Full Width Banner
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FullWidthBannerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FullWidthBannerSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Full Width Banner*
 */
type FullWidthBannerSliceVariation = FullWidthBannerSliceDefault;

/**
 * Full Width Banner Shared Slice
 *
 * - **API ID**: `full_width_banner`
 * - **Description**: A full-width banner with background image and absolutely positioned content
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FullWidthBannerSlice = prismic.SharedSlice<
  "full_width_banner",
  FullWidthBannerSliceVariation
>;

/**
 * Primary content in *Image Gallery → Default → Primary*
 */
export interface ImageGallerySliceDefaultPrimary {
  /**
   * Title field in *Image Gallery → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter the gallery title
   * - **API ID Path**: image_gallery.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Subtitle field in *Image Gallery → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter a subtitle or description
   * - **API ID Path**: image_gallery.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtitle: prismic.RichTextField;

  /**
   * Layout field in *Image Gallery → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Choose the gallery layout
   * - **Default Value**: carousel
   * - **API ID Path**: image_gallery.default.primary.layout
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  layout: prismic.SelectField<"carousel" | "mansory" | "featured", "filled">;

  /**
   * Show Thumbnails field in *Image Gallery → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: image_gallery.default.primary.showThumbnails
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  showThumbnails: prismic.BooleanField;

  /**
   * Show Navigation Arrows field in *Image Gallery → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: image_gallery.default.primary.showNavigation
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  showNavigation: prismic.BooleanField;

  /**
   * Auto Play field in *Image Gallery → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: image_gallery.default.primary.autoPlay
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  autoPlay: prismic.BooleanField;

  /**
   * Auto Play Interval (ms) field in *Image Gallery → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: 5000
   * - **API ID Path**: image_gallery.default.primary.autoPlayInterval
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  autoPlayInterval: prismic.NumberField;
}

/**
 * Primary content in *Image Gallery → Items*
 */
export interface ImageGallerySliceDefaultItem {
  /**
   * Image field in *Image Gallery → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_gallery.items[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Caption field in *Image Gallery → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter an image caption
   * - **API ID Path**: image_gallery.items[].caption
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  caption: prismic.KeyTextField;
}

/**
 * Default variation for Image Gallery Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default Image Gallery
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageGallerySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageGallerySliceDefaultPrimary>,
  Simplify<ImageGallerySliceDefaultItem>
>;

/**
 * Slice variation for *Image Gallery*
 */
type ImageGallerySliceVariation = ImageGallerySliceDefault;

/**
 * Image Gallery Shared Slice
 *
 * - **API ID**: `image_gallery`
 * - **Description**: A flexible image gallery with carousel and grid layouts, modal viewing, and navigation options
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageGallerySlice = prismic.SharedSlice<
  "image_gallery",
  ImageGallerySliceVariation
>;

/**
 * Primary content in *Multi Column Cards → Default → Primary*
 */
export interface MultiColumnCardsSliceDefaultPrimary {
  /**
   * Title field in *Multi Column Cards → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter the main title for the cards section
   * - **API ID Path**: multi_column_cards.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Subtitle field in *Multi Column Cards → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter a subtitle or description
   * - **API ID Path**: multi_column_cards.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtitle: prismic.RichTextField;

  /**
   * Number of Columns field in *Multi Column Cards → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: 3
   * - **API ID Path**: multi_column_cards.default.primary.columns
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  columns: prismic.NumberField;

  /**
   * Card Style field in *Multi Column Cards → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: default
   * - **API ID Path**: multi_column_cards.default.primary.cardStyle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cardStyle: prismic.KeyTextField;

  /**
   * Show Images field in *Multi Column Cards → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: multi_column_cards.default.primary.showImages
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  showImages: prismic.BooleanField;

  /**
   * Show Buttons field in *Multi Column Cards → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: multi_column_cards.default.primary.showButtons
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  showButtons: prismic.BooleanField;

  /**
   * Text Alignment field in *Multi Column Cards → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: center
   * - **API ID Path**: multi_column_cards.default.primary.alignment
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  alignment: prismic.KeyTextField;

  /**
   * Footer Link field in *Multi Column Cards → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link to view all items
   * - **API ID Path**: multi_column_cards.default.primary.footerLink
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  footerLink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Footer Button Text field in *Multi Column Cards → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: View All
   * - **API ID Path**: multi_column_cards.default.primary.footerButtonText
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  footerButtonText: prismic.KeyTextField;
}

/**
 * Primary content in *Multi Column Cards → Items*
 */
export interface MultiColumnCardsSliceDefaultItem {
  /**
   * Card Title field in *Multi Column Cards → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter the card title
   * - **API ID Path**: multi_column_cards.items[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Multi Column Cards → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter the card description
   * - **API ID Path**: multi_column_cards.items[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Image field in *Multi Column Cards → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: multi_column_cards.items[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Icon field in *Multi Column Cards → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: multi_column_cards.items[].icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon: prismic.ImageField<never>;

  /**
   * Link field in *Multi Column Cards → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link to learn more
   * - **API ID Path**: multi_column_cards.items[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Button Text field in *Multi Column Cards → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Learn More
   * - **API ID Path**: multi_column_cards.items[].buttonText
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  buttonText: prismic.KeyTextField;

  /**
   * Price field in *Multi Column Cards → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter price if applicable
   * - **API ID Path**: multi_column_cards.items[].price
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  price: prismic.KeyTextField;

  /**
   * Features List field in *Multi Column Cards → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter feature items (one per line)
   * - **API ID Path**: multi_column_cards.items[].features
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  features: prismic.KeyTextField;
}

/**
 * Default variation for Multi Column Cards Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default Multi Column Cards
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MultiColumnCardsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MultiColumnCardsSliceDefaultPrimary>,
  Simplify<MultiColumnCardsSliceDefaultItem>
>;

/**
 * Slice variation for *Multi Column Cards*
 */
type MultiColumnCardsSliceVariation = MultiColumnCardsSliceDefault;

/**
 * Multi Column Cards Shared Slice
 *
 * - **API ID**: `multi_column_cards`
 * - **Description**: A flexible card layout with customizable columns and card styles
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MultiColumnCardsSlice = prismic.SharedSlice<
  "multi_column_cards",
  MultiColumnCardsSliceVariation
>;

/**
 * Primary content in *Newsletter Signup → Default → Primary*
 */
export interface NewsletterSignupSliceDefaultPrimary {
  /**
   * Title field in *Newsletter Signup → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter the newsletter title
   * - **API ID Path**: newsletter_signup.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Subtitle field in *Newsletter Signup → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter a subtitle or description
   * - **API ID Path**: newsletter_signup.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtitle: prismic.RichTextField;

  /**
   * Layout field in *Newsletter Signup → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: centered
   * - **API ID Path**: newsletter_signup.default.primary.layout
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  layout: prismic.KeyTextField;

  /**
   * Show Image field in *Newsletter Signup → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: newsletter_signup.default.primary.showImage
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  showImage: prismic.BooleanField;

  /**
   * Background Image field in *Newsletter Signup → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: newsletter_signup.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Email Placeholder field in *Newsletter Signup → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter your email address
   * - **API ID Path**: newsletter_signup.default.primary.placeholder
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  placeholder: prismic.KeyTextField;

  /**
   * Button Text field in *Newsletter Signup → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Subscribe
   * - **API ID Path**: newsletter_signup.default.primary.buttonText
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  buttonText: prismic.KeyTextField;

  /**
   * Success Title field in *Newsletter Signup → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Thank you for subscribing!
   * - **API ID Path**: newsletter_signup.default.primary.successTitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  successTitle: prismic.KeyTextField;

  /**
   * Success Message field in *Newsletter Signup → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: You'll receive our latest updates soon.
   * - **API ID Path**: newsletter_signup.default.primary.successMessage
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  successMessage: prismic.KeyTextField;

  /**
   * Privacy Notice field in *Newsletter Signup → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter privacy notice text
   * - **API ID Path**: newsletter_signup.default.primary.privacyNotice
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  privacyNotice: prismic.RichTextField;

  /**
   * Features List field in *Newsletter Signup → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter feature items (one per line)
   * - **API ID Path**: newsletter_signup.default.primary.features
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  features: prismic.KeyTextField;
}

/**
 * Default variation for Newsletter Signup Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default Newsletter Signup
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type NewsletterSignupSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NewsletterSignupSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Newsletter Signup*
 */
type NewsletterSignupSliceVariation = NewsletterSignupSliceDefault;

/**
 * Newsletter Signup Shared Slice
 *
 * - **API ID**: `newsletter_signup`
 * - **Description**: A newsletter subscription form with customizable layouts and styling options
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type NewsletterSignupSlice = prismic.SharedSlice<
  "newsletter_signup",
  NewsletterSignupSliceVariation
>;

/**
 * Primary content in *PlainText → Default → Primary*
 */
export interface PlainTextSliceDefaultPrimary {
  /**
   * Title field in *PlainText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter the section title
   * - **API ID Path**: plain_text.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Description field in *PlainText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter a subtitle or description
   * - **API ID Path**: plain_text.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Call To Actions field in *PlainText → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: plain_text.default.primary.call_to_actions
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  call_to_actions: prismic.Repeatable<
    prismic.LinkField<
      string,
      string,
      unknown,
      prismic.FieldState,
      "Primary" | "Secondary"
    >
  >;

  /**
   * Horizontal Position field in *PlainText → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Choose the horizontal position of content
   * - **Default Value**: left
   * - **API ID Path**: plain_text.default.primary.horizontal_position
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  horizontal_position: prismic.SelectField<
    "left" | "center" | "right",
    "filled"
  >;

  /**
   * Vertical Position field in *PlainText → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Choose the vertical position of content
   * - **API ID Path**: plain_text.default.primary.vertical_position
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  vertical_position: prismic.SelectField<"top" | "middle" | "bottom">;

  /**
   * Content Alignment field in *PlainText → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Choose the text alignment for content
   * - **Default Value**: left
   * - **API ID Path**: plain_text.default.primary.content_alignment
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  content_alignment: prismic.SelectField<"left" | "center" | "right", "filled">;
}

/**
 * Default variation for PlainText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PlainTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PlainTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PlainText*
 */
type PlainTextSliceVariation = PlainTextSliceDefault;

/**
 * PlainText Shared Slice
 *
 * - **API ID**: `plain_text`
 * - **Description**: PlainText
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PlainTextSlice = prismic.SharedSlice<
  "plain_text",
  PlainTextSliceVariation
>;

/**
 * Primary content in *Pricing Table → Default → Primary*
 */
export interface PricingTableSliceDefaultPrimary {
  /**
   * Title field in *Pricing Table → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter the pricing table title
   * - **API ID Path**: pricing_table.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Subtitle field in *Pricing Table → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter a subtitle or description
   * - **API ID Path**: pricing_table.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtitle: prismic.RichTextField;

  /**
   * Layout field in *Pricing Table → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: grid
   * - **API ID Path**: pricing_table.default.primary.layout
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  layout: prismic.KeyTextField;

  /**
   * Highlight Plan (1-based index) field in *Pricing Table → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: 1
   * - **API ID Path**: pricing_table.default.primary.highlightPlan
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  highlightPlan: prismic.NumberField;

  /**
   * Show Features field in *Pricing Table → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: pricing_table.default.primary.showFeatures
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  showFeatures: prismic.BooleanField;

  /**
   * Show Buttons field in *Pricing Table → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: pricing_table.default.primary.showButtons
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  showButtons: prismic.BooleanField;

  /**
   * Footer Text field in *Pricing Table → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter any additional footer text
   * - **API ID Path**: pricing_table.default.primary.footerText
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  footerText: prismic.RichTextField;
}

/**
 * Primary content in *Pricing Table → Items*
 */
export interface PricingTableSliceDefaultItem {
  /**
   * Plan Name field in *Pricing Table → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter the plan name
   * - **API ID Path**: pricing_table.items[].name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Plan Description field in *Pricing Table → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter a brief description
   * - **API ID Path**: pricing_table.items[].description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * Price field in *Pricing Table → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter the price (e.g., $29/month)
   * - **API ID Path**: pricing_table.items[].price
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  price: prismic.KeyTextField;

  /**
   * Period field in *Pricing Table → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter the billing period (e.g., /month, /year)
   * - **API ID Path**: pricing_table.items[].period
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  period: prismic.KeyTextField;

  /**
   * Badge field in *Pricing Table → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter a badge text (e.g., 'Most Popular')
   * - **API ID Path**: pricing_table.items[].badge
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  badge: prismic.KeyTextField;

  /**
   * Features List field in *Pricing Table → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter feature items (one per line)
   * - **API ID Path**: pricing_table.items[].features
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  features: prismic.KeyTextField;

  /**
   * Plan Link field in *Pricing Table → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link to choose this plan
   * - **API ID Path**: pricing_table.items[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Button Text field in *Pricing Table → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Choose Plan
   * - **API ID Path**: pricing_table.items[].buttonText
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  buttonText: prismic.KeyTextField;
}

/**
 * Default variation for Pricing Table Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default Pricing Table
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PricingTableSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PricingTableSliceDefaultPrimary>,
  Simplify<PricingTableSliceDefaultItem>
>;

/**
 * Slice variation for *Pricing Table*
 */
type PricingTableSliceVariation = PricingTableSliceDefault;

/**
 * Pricing Table Shared Slice
 *
 * - **API ID**: `pricing_table`
 * - **Description**: A flexible pricing table with multiple layout options and customizable features
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PricingTableSlice = prismic.SharedSlice<
  "pricing_table",
  PricingTableSliceVariation
>;

/**
 * Primary content in *Product Carousel → Default → Primary*
 */
export interface ProductCarouselSliceDefaultPrimary {
  /**
   * Title field in *Product Carousel → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter the carousel title
   * - **API ID Path**: product_carousel.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Subtitle field in *Product Carousel → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter a subtitle or description
   * - **API ID Path**: product_carousel.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtitle: prismic.RichTextField;

  /**
   * Number of Products to Show field in *Product Carousel → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: 10
   * - **API ID Path**: product_carousel.default.primary.productCount
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  productCount: prismic.NumberField;

  /**
   * Items Per View field in *Product Carousel → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: 3
   * - **API ID Path**: product_carousel.default.primary.itemsPerView
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  itemsPerView: prismic.NumberField;

  /**
   * Show Navigation Arrows field in *Product Carousel → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: product_carousel.default.primary.showNavigation
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  showNavigation: prismic.BooleanField;

  /**
   * Show Dots Navigation field in *Product Carousel → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: product_carousel.default.primary.showDots
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  showDots: prismic.BooleanField;
}

/**
 * Default variation for Product Carousel Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default Product Carousel with Auto-fetch
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProductCarouselSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProductCarouselSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Product Carousel*
 */
type ProductCarouselSliceVariation = ProductCarouselSliceDefault;

/**
 * Product Carousel Shared Slice
 *
 * - **API ID**: `product_carousel`
 * - **Description**: An animated product carousel that automatically fetches products from the API with customizable navigation and auto-play options
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProductCarouselSlice = prismic.SharedSlice<
  "product_carousel",
  ProductCarouselSliceVariation
>;

/**
 * Primary content in *Stats Counter → Default → Primary*
 */
export interface StatsCounterSliceDefaultPrimary {
  /**
   * Title field in *Stats Counter → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter the stats section title
   * - **API ID Path**: stats_counter.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Subtitle field in *Stats Counter → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter a subtitle or description
   * - **API ID Path**: stats_counter.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtitle: prismic.RichTextField;

  /**
   * Layout field in *Stats Counter → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: grid
   * - **API ID Path**: stats_counter.default.primary.layout
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  layout: prismic.KeyTextField;

  /**
   * Animation Duration (ms) field in *Stats Counter → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: 2000
   * - **API ID Path**: stats_counter.default.primary.animationDuration
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  animationDuration: prismic.NumberField;

  /**
   * Show Icons field in *Stats Counter → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: stats_counter.default.primary.showIcons
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  showIcons: prismic.BooleanField;

  /**
   * Text Alignment field in *Stats Counter → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: center
   * - **API ID Path**: stats_counter.default.primary.alignment
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  alignment: prismic.KeyTextField;

  /**
   * Footer Text field in *Stats Counter → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter any additional footer text
   * - **API ID Path**: stats_counter.default.primary.footerText
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  footerText: prismic.RichTextField;
}

/**
 * Primary content in *Stats Counter → Items*
 */
export interface StatsCounterSliceDefaultItem {
  /**
   * Statistic Value field in *Stats Counter → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter the numeric value
   * - **API ID Path**: stats_counter.items[].value
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  value: prismic.KeyTextField;

  /**
   * Statistic Label field in *Stats Counter → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter the statistic label
   * - **API ID Path**: stats_counter.items[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Description field in *Stats Counter → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter a description for this statistic
   * - **API ID Path**: stats_counter.items[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Icon field in *Stats Counter → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: stats_counter.items[].icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon: prismic.ImageField<never>;

  /**
   * Prefix field in *Stats Counter → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter prefix (e.g., $, €)
   * - **API ID Path**: stats_counter.items[].prefix
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  prefix: prismic.KeyTextField;

  /**
   * Suffix field in *Stats Counter → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter suffix (e.g., +, %, K, M)
   * - **API ID Path**: stats_counter.items[].suffix
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  suffix: prismic.KeyTextField;
}

/**
 * Default variation for Stats Counter Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default Stats Counter
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type StatsCounterSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<StatsCounterSliceDefaultPrimary>,
  Simplify<StatsCounterSliceDefaultItem>
>;

/**
 * Slice variation for *Stats Counter*
 */
type StatsCounterSliceVariation = StatsCounterSliceDefault;

/**
 * Stats Counter Shared Slice
 *
 * - **API ID**: `stats_counter`
 * - **Description**: An animated statistics counter with customizable layouts and scroll-triggered animations
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type StatsCounterSlice = prismic.SharedSlice<
  "stats_counter",
  StatsCounterSliceVariation
>;

/**
 * Primary content in *Testimonials → Default → Primary*
 */
export interface TestimonialsSliceDefaultPrimary {
  /**
   * Title field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter the testimonials section title
   * - **API ID Path**: testimonials.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Subtitle field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter a subtitle or description
   * - **API ID Path**: testimonials.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtitle: prismic.RichTextField;

  /**
   * Layout field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: carousel
   * - **API ID Path**: testimonials.default.primary.layout
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  layout: prismic.KeyTextField;

  /**
   * Show Navigation Arrows field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: testimonials.default.primary.showNavigation
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  showNavigation: prismic.BooleanField;

  /**
   * Show Dots Navigation field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: testimonials.default.primary.showDots
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  showDots: prismic.BooleanField;

  /**
   * Auto Play field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: testimonials.default.primary.autoPlay
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  autoPlay: prismic.BooleanField;

  /**
   * Auto Play Interval (ms) field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: 5000
   * - **API ID Path**: testimonials.default.primary.autoPlayInterval
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  autoPlayInterval: prismic.NumberField;

  /**
   * Show Star Ratings field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: testimonials.default.primary.showRatings
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  showRatings: prismic.BooleanField;
}

/**
 * Primary content in *Testimonials → Items*
 */
export interface TestimonialsSliceDefaultItem {
  /**
   * Testimonial Quote field in *Testimonials → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter the customer testimonial quote
   * - **API ID Path**: testimonials.items[].quote
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  quote: prismic.RichTextField;

  /**
   * Customer Name field in *Testimonials → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter the customer's name
   * - **API ID Path**: testimonials.items[].name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Job Title field in *Testimonials → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter the customer's job title
   * - **API ID Path**: testimonials.items[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Company field in *Testimonials → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter the customer's company name
   * - **API ID Path**: testimonials.items[].company
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  company: prismic.KeyTextField;

  /**
   * Customer Avatar field in *Testimonials → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.items[].avatar
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  avatar: prismic.ImageField<never>;

  /**
   * Star Rating (1-5) field in *Testimonials → Items*
   *
   * - **Field Type**: Number
   * - **Placeholder**: 4.5
   * - **API ID Path**: testimonials.items[].rating
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  rating: prismic.NumberField;
}

/**
 * Default variation for Testimonials Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default Testimonials
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TestimonialsSliceDefaultPrimary>,
  Simplify<TestimonialsSliceDefaultItem>
>;

/**
 * Slice variation for *Testimonials*
 */
type TestimonialsSliceVariation = TestimonialsSliceDefault;

/**
 * Testimonials Shared Slice
 *
 * - **API ID**: `testimonials`
 * - **Description**: A testimonials section with carousel and grid layouts, featuring customer reviews with ratings and author information
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialsSlice = prismic.SharedSlice<
  "testimonials",
  TestimonialsSliceVariation
>;

/**
 * Primary content in *TextAndImage → Default → Primary*
 */
export interface TextAndImageSliceDefaultPrimary {
  /**
   * Title field in *TextAndImage → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_and_image.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Description field in *TextAndImage → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_and_image.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Primary Button field in *TextAndImage → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: text_and_image.default.primary.primary_button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  primary_button: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Image field in *TextAndImage → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: text_and_image.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Image Position field in *TextAndImage → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Choose the default image position
   * - **API ID Path**: text_and_image.default.primary.image_position
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  image_position: prismic.SelectField<"right" | "left">;
}

/**
 * Default variation for TextAndImage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Image on the right, text content and CTA on the left.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextAndImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextAndImageSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TextAndImage*
 */
type TextAndImageSliceVariation = TextAndImageSliceDefault;

/**
 * TextAndImage Shared Slice
 *
 * - **API ID**: `text_and_image`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextAndImageSlice = prismic.SharedSlice<
  "text_and_image",
  TextAndImageSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      MegaMenuDocument,
      MegaMenuDocumentData,
      MegaMenuDocumentDataMenuItemsChildLinksItem,
      MegaMenuDocumentDataMenuItemsItem,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      PageDocumentDataSlices1Slice,
      AllDocumentTypes,
      FaqAccordionSlice,
      FaqAccordionSliceDefaultPrimary,
      FaqAccordionSliceDefaultItem,
      FaqAccordionSliceVariation,
      FaqAccordionSliceDefault,
      FeatureGridAnimatedSlice,
      FeatureGridAnimatedSliceDefaultPrimary,
      FeatureGridAnimatedSliceDefaultItem,
      FeatureGridAnimatedSliceVariation,
      FeatureGridAnimatedSliceDefault,
      FullWidthBannerSlice,
      FullWidthBannerSliceDefaultPrimary,
      FullWidthBannerSliceVariation,
      FullWidthBannerSliceDefault,
      ImageGallerySlice,
      ImageGallerySliceDefaultPrimary,
      ImageGallerySliceDefaultItem,
      ImageGallerySliceVariation,
      ImageGallerySliceDefault,
      MultiColumnCardsSlice,
      MultiColumnCardsSliceDefaultPrimary,
      MultiColumnCardsSliceDefaultItem,
      MultiColumnCardsSliceVariation,
      MultiColumnCardsSliceDefault,
      NewsletterSignupSlice,
      NewsletterSignupSliceDefaultPrimary,
      NewsletterSignupSliceVariation,
      NewsletterSignupSliceDefault,
      PlainTextSlice,
      PlainTextSliceDefaultPrimary,
      PlainTextSliceVariation,
      PlainTextSliceDefault,
      PricingTableSlice,
      PricingTableSliceDefaultPrimary,
      PricingTableSliceDefaultItem,
      PricingTableSliceVariation,
      PricingTableSliceDefault,
      ProductCarouselSlice,
      ProductCarouselSliceDefaultPrimary,
      ProductCarouselSliceVariation,
      ProductCarouselSliceDefault,
      StatsCounterSlice,
      StatsCounterSliceDefaultPrimary,
      StatsCounterSliceDefaultItem,
      StatsCounterSliceVariation,
      StatsCounterSliceDefault,
      TestimonialsSlice,
      TestimonialsSliceDefaultPrimary,
      TestimonialsSliceDefaultItem,
      TestimonialsSliceVariation,
      TestimonialsSliceDefault,
      TextAndImageSlice,
      TextAndImageSliceDefaultPrimary,
      TextAndImageSliceVariation,
      TextAndImageSliceDefault,
    };
  }
}
