import { NavItem } from "@/types";

//Info: The following data is used for the sidebar navigation and Cmd K bar.
export const navItems: NavItem[] = [
  {
    title: "Sản phẩm",
    url: "/admin/products",
    icon: "product",
    shortcut: ["p", "p"],
    isActive: false,
    items: [],
  },
  {
    title: "Danh mục",
    url: "/admin/categories",
    icon: "folder",
    shortcut: ["c", "c"],
    isActive: false,
    items: [],
  },
  {
    title: "Người dùng",
    url: "/admin/users",
    icon: "users",
    shortcut: ["u", "u"],
    isActive: false,
    items: [],
  },
  {
    title: "Đơn hàng",
    url: "/admin/orders",
    icon: "package",
    shortcut: ["o", "o"],
    isActive: false,
    items: [],
  },
  {
    title: "Khóa học",
    url: "/admin/courses",
    icon: "book-audio",
    shortcut: ["c", "o"],
    isActive: false,
    items: [],
  },
  {
    title: "Cuộc thi",
    url: "/admin/contests",
    icon: "trophy",
    shortcut: ["c", "t"],
    isActive: false,
    items: [],
  },
  {
    title: "Kiểu tóc",
    url: "/admin/hairstyles",
    icon: "scissors",
    shortcut: ["h", "h"],
    isActive: false,
    items: [],
  },
  {
    title: "Bài dự thi",
    url: "/admin/submissions",
    icon: "award",
    shortcut: ["s", "s"],
    isActive: false,
    items: [],
  },
  {
    title: "Trang",
    url: "/admin/pages",
    icon: "page",
    shortcut: ["p", "a"],
    isActive: false,
    items: [],
  },
  {
    title: "Đánh giá sản phẩm",
    url: "/admin/product-reviews",
    icon: "star",
    shortcut: ["r", "r"],
    isActive: false,
    items: [],
  },
  {
    title: "Đại lý/CTV",
    url: "/admin/affiliate",
    icon: "user-check",
    shortcut: ["a", "f"],
    isActive: false,
    items: [
      {
        title: "Yêu cầu đăng ký",
        url: "/admin/affiliate-approvals",
        icon: "user-check",
        shortcut: ["a", "y"],
        isActive: false,
        items: [],
      },
      {
        title: "Liên kết",
        url: "/admin/affiliate-links",
        icon: "link",
        shortcut: ["a", "k"],
        isActive: false,
        items: [],
      },
      {
        title: "Rút tiền",
        url: "/admin/affiliate-withdrawal",
        icon: "money",
        shortcut: ["a", "r"],
        isActive: false,
        items: [],
      },
      {
        title: "Giao dịch",
        url: "/admin/affiliate-transaction",
        icon: "credit-card",
        shortcut: ["a", "t"],
        isActive: false,
        items: [],
      },
    ],
  },
  {
    title: "Phân tích",
    url: "/admin/analytics",
    icon: "chart",
    shortcut: ["a", "a"],
    isActive: false,
    items: [],
  },
];
