import {
  AlertTriangle,
  ArrowRight,
  Book,
  Check,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Command,
  CreditCard,
  File,
  FileText,
  Folder,
  HelpCircle,
  Image as Photo,
  Laptop,
  LayoutDashboard,
  Loader2,
  LogIn,
  Package,
  Scissors,
  ShoppingBag,
  Moon,
  MoreVertical,
  Percent,
  Pizza,
  Plus,
  Settings,
  Sun,
  Trophy,
  Trash2,
  User,
  UserCheck,
  UserCircle,
  UserPen,
  Users,
  UserX,
  X,
  Award,
  Star,
  Link,
  BookAudio,
  ChartNoAxesCombined as Chart,
  type LucideProps,
  DollarSign,
} from "lucide-react";

export type Icon = React.ComponentType<LucideProps>;

export const Icons = {
  dashboard: LayoutDashboard,
  logo: Command,
  login: LogIn,
  close: X,
  product: ShoppingBag,
  folder: Folder,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronUp: ChevronUp,
  trash: Trash2,
  employee: UserX,
  post: FileText,
  page: File,
  userPen: UserPen,
  user2: UserCircle,
  media: Photo,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertTriangle,
  user: User,
  arrowRight: ArrowRight,
  help: HelpCircle,
  pizza: Pizza,
  sun: Sun,
  moon: Moon,
  laptop: Laptop,
  check: Check,
  book: Book,
  "book-audio": BookAudio,
  users: Users,
  "user-check": UserCheck,
  percent: Percent,
  package: Package,
  scissors: Scissors,
  trophy: Trophy,
  award: Award,
  star: Star,
  link: Link,
  chart: Chart,
  money: DollarSign,
  "credit-card": CreditCard,
};
