// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  before_after_slider: dynamic(() => import("./BeforeAfterSlider")),
  faq_accordion: dynamic(() => import("./FAQAccordion")),
  feature_grid_animated: dynamic(() => import("./FeatureGridAnimated")),
  full_width_banner: dynamic(() => import("./FullWidthBanner")),
  image_gallery: dynamic(() => import("./ImageGallery")),
  multi_column_cards: dynamic(() => import("./MultiColumnCards")),
  newsletter_signup: dynamic(() => import("./NewsletterSignup")),
  plain_text: dynamic(() => import("./PlainText")),
  pricing_table: dynamic(() => import("./PricingTable")),
  product_carousel: dynamic(() => import("./ProductCarousel")),
  stats_counter: dynamic(() => import("./StatsCounter")),
  testimonials: dynamic(() => import("./Testimonials")),
  text_and_image: dynamic(() => import("./TextAndImage")),
};
